#################################
#     Background-Blurring       #
#################################

blur:
{
  method = "dual_kawase";
}

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
];

backend = "glx";
