#################################
#     Background-Blurring       #
#################################
shadow = false;
shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'utility'",
  "window_type = 'popup_menu'",
  "window_type = 'dropdown_menu'",
  "_GTK_FRAME_EXTENTS@:c",
];

fading = true;
fade-in-step = 0.125;
fade-out-step = 0.125;
fade-delta = 10

inactive-opacity = 0.95;
frame-opacity = 1;
focus-exclude = [
    "class_g = 'awesome'",
    "class_g = 'Rofi'",
    "window_type = 'utility'",
];

blur:
{
  method = "dual_kawase";
}
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'utility'",
  "window_type = 'popup_menu'",
  "window_type = 'dropdown_menu'",
  "_GTK_FRAME_EXTENTS@:c",
];

backend = "egl";
mark-wmwin-focused = false;
mark-ovredir-focused = false;
detect-rounded-corners = false;
detect-client-opacity = false;
use-ewmh-active-win = false;
unredir-if-possible = true;
detect-transient = true;
use-damage = true;
no-ewmh-fullscreen = true;
transparent-clipping = false;

